application: tahoeperf-1
version: 1
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "5s"

handlers:

- url: /api.*
  script: api.app

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /
  static_dir: static/


libraries:
- name: webapp2
  version: "2.5.2"
- name: webob
  version: "1.2.3"
