application: tahoeperf-1
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/
  static_dir: frontend/static/

- url: /
  static_files: static/html/index.html
  upload: static/html

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/favicon.png
  upload: static/favicon.png
  mime_type: image/png

#libraries:
#- name: webapp2
#  version: "2.5.1"
