application: tahoeperf-1
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /api$
  script: frontend.api.app

- url: /$
  static_files: frontend/static/index.html
  upload: frontend/static/index.html

- url: /favicon.ico
  static_files: frontend/static/icon.png
  upload: frontend/static/icon.png
  mime_type: image/png

- url: /
  static_dir: frontend/static/

libraries:
- name: webapp2
  version: "2.5.1"
