application: tahoeperf-1
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: frontend/static/html/index.html
  upload: frontend/static/html

- url: /static/
  static_dir: frontend/static/

- url: /robots.txt
  static_files: frontend/static/robots.txt
  upload: frontend/static/robots.txt

- url: /favicon.ico
  static_files: frontend/static/icon.png
  upload: frontend/static/icon.png
  mime_type: image/png

- url: /api.*
  script: frontend.api.app

#libraries:
#- name: webapp2
#  version: "2.5.1"
