application: tahoeperf-1
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /api.*
  script: frontend.api.app

- url: /
  static_files: frontend/static/index.html
  upload: frontend/static/index.html

- url: /
  static_dir: frontend/static/


libraries:
- name: webapp2
  version: "2.5.2"
- name: webob
  version: "1.2.3"
